#!/bin/zsh

###############################################################################
# History settings
###############################################################################

export HISTTIMEFORMAT="%Y/%m/%d %H:%M:%S:   "
export HISTSIZE=50000                                 # History lines stored in mememory.
export SAVEHIST=50000                                 # History lines stored on disk.
export HISTCONTROL=ignoredups
export HISTIGNORE="&:l:ls:lt:la:lsa:ll:exit:history"
setopt INC_APPEND_HISTORY                             # Immediately append commands to history file.
setopt HIST_IGNORE_ALL_DUPS                           # Never add duplicate entries.
setopt HIST_IGNORE_SPACE                              # Ignore commands that start with a space.
setopt HIST_REDUCE_BLANKS                             # Remove unnecessary blank lines.

###############################################################################
# Completions
###############################################################################

# AWS Command Completion
if [ -f /usr/local/bin/aws_completer ] ; then
  complete -C /usr/local/bin/aws_completer aws
fi

# Source gcloud
if [ -f /usr/local/bin/google-cloud-sdk/path.bash.inc ] ; then
  source "/usr/local/bin/google-cloud-sdk/path.bash.inc"
fi

# Source gcloud completion
if [ -f /usr/local/bin/google-cloud-sdk/completion.bash.inc ] ; then
  source "/usr/local/bin/google-cloud-sdk/completion.bash.inc"
fi

# kubectl completion
# https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-mac/
source <(kubectl completion bash)

# Source git completion
# Source - https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
# if [ -f ${HOME}/.monkeydotfiles/git/git-completion.sh ] ; then
#   source "${HOME}/.monkeydotfiles/git/git-completion.sh"
# fi

# Source cheat completion
if [ -f ${HOME}/.monkeydotfile/cheat/cheat-completion.sh ] ; then
  source "${HOME}/.monkeydotfiles/cheat/cheat-completion.sh"
fi

# explain.sh begins
# https://www.tecmint.com/explain-shell-commands-in-the-linux-shell/
explain () {
  if [ "$#" -eq 0 ]; then
    while read  -p "Command: " cmd; do
      curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols) --data-urlencode "q=$cmd"
    done
    echo "Bye!"
  elif [ "$#" -eq 1 ]; then
    curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols) --data-urlencode "q=$1"
  else
  echo "Usage"
  echo "explain                  interactive mode."
  echo "explain 'cmd -o | ...'   one quoted command to explain it."
  fi
}

# Set gpg prompts to use the terminal
GPG_TTY=$(tty)
export GPG_TTY

# Source Fuzzy Search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

###############################################################################
# Pathing
###############################################################################

# Visual Studio Code
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"

# Python
# Python is controlled with pyenv. Use it.

# Pyenv PATH export
# Remember to `pyenv global 3.9.12 2.7.18` or whatever versions I have installed
export PATH="$(pyenv root)/shims:$PATH"

###############################################################################
# Misc Exports
###############################################################################

# Brew export
# export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"

# Enable Buildkit
export DOCKER_BUILDKIT=1

# NPM Token
export NPM_TOKEN=be7e43c9-d57d-424b-ae27-9f3e7828d7df

# Terragrunt cache location
export TERRAGRUNT_DOWNLOAD=${HOME}/.terragrunt/cache

# Terraform plugin location
export TF_PLUGIN_CACHE_DIR=${HOME}/.terraform.d/plugin-cache

# Terragrunt Local
# Use local IAM role instead of Atlantis
export TERRAGRUNT_LOCAL=true

# CirleCI Token
# export CIRCLECI_TOKEN=

# PagerDuty Token
# export PAGERDUTY_TOKEN=

# New Relic
# export NEW_RELIC_ACCOUNT_ID=
# export NEW_RELIC_API_KEY=
# export NEW_RELIC_ADMIN_API_KEY=
# export NEW_RELIC_REGION=us

###############################################################################
# OH-MY-ZSH Settings
###############################################################################

export ZSH="$HOME/.oh-my-zsh"

if [ -f $ZSH/oh-my-zsh.sh ] ; then
  source "$ZSH/oh-my-zsh.sh"
fi
source 

# Set the update mode to reminder
zstyle ':omz:update' mode reminder

# Set the theme(s)
ZSH_THEME="agnoster"

# Enable plugins
plugins=(git web-search)

# Set the terminal to only show the username
# https://catalins.tech/improve-mac-terminal
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
  fi
}

# zsh-autosuggestions settings.
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

echo "  Zsh exports sourced."
