#!/bin/bash

set -e

function print_usage {
  echo
  echo "USAGE: monkeydotfiles [OPTIONS]"
  echo
  echo "This script will bootstrap all the user config files for:"
  echo "  - aws-auth"
  echo "  - bash_profile"
  echo "  - git"
  echo "  - liquidprompt"
  echo "  - lpass"
  echo "  - ssh"
  echo "  - sublime"
  echo
  echo "Options:"
  echo
  echo -e "  --all\t\tBootstrap all the config files."
  echo -e "  --backup\tBackup all the existing config files. Good way to preserve everything while testing. Runs by default."
  echo -e "  --sublime\tOnly bootstrap Sublime Text 3 files."
  echo
}

function backup_files () {
  echo
  echo "INFO: Backing up files"

  mkdir -v ~/.monkeydotfiles/backup

  mv -fv /usr/loca/bin/aws-auth ~/.monkeydotfiles/backup/
  mv -fv ~/.bash_profile ~/.monkeydotfiles/backup/
  mv -fv ~/.bashrc ~/.monkeydotfiles/backup/
  mv -fv ~/.git-autocompletion.sh ~/.monkeydotfiles/backup/
  mv -fv ~/.gitattributes ~/.monkeydotfiles/backup/
  mv -fv ~/.gitconfig ~/.monkeydotfiles/backup/
  mv -fv ~/.config/liquidprompt ~/.monkeydotfiles/backup/
  mv -fv ~/.lpass/username ~/.monkeydotfiles/backup/
  mv -fv ~/.ssh ~/.monkeydotfiles/backup/
}

function symlink_env () {
  echo
  echo "INFO: Symlinking environment"

  ln -fsv ~/.monkeydotfiles/aws-auth/aws-auth /usr/local/bin/aws-auth
  ln -fsv ~/.monkeydotfiles/bash/bash_profile ~/.bash_profile
  ln -fsv ~/.monkeydotfiles/git ~/.git
  ln -fsv ~/.monkeydotfiles/git/gitconfig ~/.gitconfig
  ln -fsv ~/.monkeydotfiles/liquidprompt/liquidprompt ~/.config/liquidprompt
  ln -fsv ~/.monkeydotfiles/lpass/username ~/.lpass/username
  ln -fsv ~/.monkeydotfiles/ssh ~/.ssh
}

function symlink_sublime () {
  
  function close_sl () {
    local pid=""

    pid="$(ps -A | grep '/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text' | grep -v 'grep' | awk '{print $1}')"

    kill "$pid"
  }

  close_sl

  # Remove all the current/default installed packages or settings
  rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/*
  rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/*

  # Copy over this default file
  cp ~/.monkeydotfiles/sublime/Package\ Control.sublime-package ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/

  # Symlink Package Control with all the listed packages to be installed
  if [ ! -d ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/ ] ; then
    mkdir -v ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
  fi
  ln -fsv ~/.monkeydotfiles/sublime/Package\ Control.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Package\ Control.sublime-settings

  # Open Sublime and wait 30s for it to install everything
  echo "###############################################"
  echo
  echo "SUBLIME IS INSTALLING PACKAGES"
  echo "PLEASE WAIT TILL AFTER IT CLOSES TO USE SUBLIME"
  echo
  echo "###############################################"
  sublime
  sleep 30

  # Close Sublime again
  close_sl

  echo
  echo "INFO: Symlinking Sublime"

  if [ ! -d ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SublimeLinter ] ; then
    mkdir -v ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SublimeLinter
  fi

  ln -fsv ~/.monkeydotfiles/sublime/Monokai\ \(SL\).tmTheme ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SublimeLinter/Monokai\ \(SL\).tmTheme
  ln -fsv ~/.monkeydotfiles/sublime/Anaconda.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Anaconda.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/Default\ \(OSX\).sublime-keymap ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Default\ \(OSX\).sublime-keymap
  ln -fsv ~/.monkeydotfiles/sublime/Git\ Commit.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Git\ Commit.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/JSON.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/JSON.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/Markdown\ Extended.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Markdown\ Extended.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/Markdown.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Markdown.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/Python.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Python.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/SBSCompare.tmTheme ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SBSCompare.tmTheme
  ln -fsv ~/.monkeydotfiles/sublime/SBSCompareScheme.sublime-color-scheme ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SBSCompareScheme.sublime-color-scheme
  ln -fsv ~/.monkeydotfiles/sublime/SBSCompareTheme.tmTheme ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SBSCompareTheme.tmTheme
  ln -fsv ~/.monkeydotfiles/sublime/SublimeLinter.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SublimeLinter.sublime-settings
  ln -fsv ~/.monkeydotfiles/sublime/Terraform.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Terraform.sublime-settings
}

function source_bash () {
  echo
  echo "INFO: Sourcing .bash_profile"
  source ~/.bash_profile
}

function install () {
  local _backup=false
  local _env=false
  local _sublime=false

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --all)
        _backup=true
        _env=true
        _sublime=true
        shift
        ;;
      --backup)
        _backup=true
        shift
        ;;
      --sublime)
        _sublime=true
        shift
        ;;
      --help)
        print_usage
        exit 1
        ;;
      *)
        echo "ERROR!"
        exit 1
        ;;
    esac
  done

  echo "$_backup"
  echo "$_env"
  echo "$_sublime"

  if [[ "$_backup" = true && "$_env" = true && "$_sublime" = true ]] ; then
    backup_files
    symlink_env
    symlink_sublime
    source_bash

    echo
    echo "monkeydotfiles --all complete"
  elif [[ "$_backup" = true && "$_env" = false && "$_sublime" = false ]] ; then
    backup_files

    echo
    echo "monkeydotfiles --backup complete"
  elif [[ "$_sublime" = true && "$_env" = false && "$_backup" = false ]]; then
    symlink_sublime

    echo
    echo "monkeydotfiles --sublime complete"
  fi
}

install "$@"

