#!/usr/bin/env bash

set -e

skip_system_packages="${1}"

os_type="$(uname -s)"

apt_packages="curl git zsh" 
# proute2 python3-pip ripgrep tmux vim-gtk zsh"
apt_packages_optional=
# "gnupg htop jq pwgen shellcheck unzip"

brew_packages="git pyenv vim fzf awscli"
brew_packages_optional="gnupg htop jq pwgen shellcheck tree"


###############################################################################
# Detect OS and distro type
###############################################################################

function no_system_packages() {
cat << EOF
System package installation isn't supported with your OS / distro.

Please install any dependent packages on your own. You can view the list at:

    https://github.com/jknsware/.monkeydotfiles/blob/master/monkeyzshdotfiles

Then re-run the script and explicitly skip installing system packages:

    bash <(curl -sS https://raw.githubusercontent.com/jknsware/.monkeydotfiles/master/monkeyzshdotfiles) --skip-system-packages
EOF

exit 1
}

case "${os_type}" in
    Linux*)
        os_type="Linux"

        if [ !  -f "/etc/debian_version" ]; then
           [ -z "${skip_system_packages}" ] && no_system_packages
        fi

        ;;
    Darwin*) os_type="macOS";;
    *)
        os_type="Other"

        [ -z "${skip_system_packages}" ] && no_system_packages

        ;;
esac

###############################################################################
# Install packages using your OS' package manager
###############################################################################

function apt_install_packages {
    # shellcheck disable=SC2086
    sudo apt-get update && sudo apt-get install -y ${apt_packages} ${apt_packages_optional}
}

function brew_install_self {
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

function brew_install_packages {
    [ -x "$(command -v brew > /dev/null 2>&1)" ] && brew_install_self

    brew install ${brew_packages} ${brew_packages_optional}
}

function display_packages {
    if [ "${os_type}" == "Linux" ]; then
        echo "${apt_packages} ${apt_packages_optional}"
    else
        echo "${brew_packages} ${brew_packages_optional}"
    fi
}

if [ -z "${skip_system_packages}" ]; then
cat << EOF

If you choose yes, all of the system packages below will be installed:

$(display_packages)

If you choose no, the above packages will not be installed and this script
will exit. This gives you a chance to edit the list of packages if you don't
agree with any of the decisions.

The packages listed after zsh are technically optional but are quite useful.
Keep in mind if you don't install pwgen you won't be able to generate random
passwords using a custom alias that's included in these dotfiles.

EOF
    while true; do
        read -rp "Do you want to install the above packages? (y/n) " yn
        case "${yn}" in
            [Yy]*)
                if [ "${os_type}" == "Linux" ]; then
                    apt_install_packages
                else
                    brew_install_packages
                fi

                break;;
            [Nn]*) exit 0;;
            *) echo "Please answer y or n";;
        esac
    done
else
    echo "System package installation was skipped!"
fi

###############################################################################
# Install Oh My Zsh
###############################################################################

sh -c "$(curl https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Rename default .zshrc
mv "${HOME}/.zshrc" "${HOME}/.zshrc.orignal"

###############################################################################
# Clone dotfiles
###############################################################################

read -rep $'\nWhere do you want to clone these dotfiles to [~/.monkeydotfiles]? ' clone_path
clone_path="${clone_path:-"${HOME}/.monkeydotfiles"}"

# Ensure path doesn't exist.
while [ -e "${clone_path}" ]; do
    read -rep $'\nPath exists, try again? (y) ' y
    case "${y}" in
        [Yy]*)

            break;;
        *) echo "Please answer y or CTRL+c the script to abort everything";;
    esac
done

echo

# This is used to locally develop the install script.
if [ "${DEBUG}" == "1" ]; then
    cp -R "${PWD}/." "${clone_path}"
else
    git clone https://github.com/jknsware/.monkeydotfiles "${clone_path}"
fi

###############################################################################
# Create initial directories
# Set up a few standard directories based on:
#   https://wiki.archlinux.org/title/XDG_Base_Directory
###############################################################################

mkdir -p "${HOME}/.config/zsh" "${HOME}/.cache/zsh" \
    "${HOME}/.local/bin" "${HOME}/.local/share" \
    "${HOME}/.local/state" "${HOME}/.terragrunt/cache" \
    "${HOME}/.terraform.d/plugin-cache"

###############################################################################
# Install zsh plugins
###############################################################################

"${clone_path}/.local/bin/update-zsh-plugins"

###############################################################################
# Carefully create symlinks
###############################################################################

cat << EOF

-------------------------------------------------------------------------------

ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv"
ln -fs "${clone_path}/.config/zsh/zsh_aliases" "${HOME}/.config/zsh/zsh_aliases"
ln -fs "${clone_path}/.config/zsh/zsh_docker" "${HOME}/.config/zsh/zsh_docker"
ln -fs "${clone_path}/.config/zsh/zsh_exports" "${HOME}/.config/zsh/zsh_exports"
ln -fs "${clone_path}/.config/zsh/zsh_git" "${HOME}/.config/zsh/zsh_git"
ln -fs "${clone_path}/.config/zsh/zsh_plugins" "${HOME}/.config/zsh/zsh_plugins"
ln -fs "${clone_path}/.local/bin/update-zsh-plugins" "${HOME}/.local/bin/update-zsh-plugins"

-------------------------------------------------------------------------------

A potentially dangerous action is about to happen. The above files are going to
get forcefully symlinked.

What does that mean?

Any config files you have on the right hand side of the paths are going to get
overwritten with the files that come with my monkeyzshdotfiles (left side).

If you care about your original config files now would be the time to back
them up. They will ALL be overwritten if you say yes to the prompt below.
EOF

while true; do
  read -rep $'\nReady to continue and apply the symlinks? (y) ' y
  case "${y}" in
      [Yy]*)

          break;;
      *) echo "Please answer y or CTRL+c the script to abort everything";;
  esac
done

ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv" \
    && ln -fs "${clone_path}/.config/zsh/zsh_aliases" "${HOME}/.config/zsh/zsh_aliases" \
    && ln -fs "${clone_path}/.config/zsh/zsh_docker" "${HOME}/.config/zsh/zsh_docker" \
    && ln -fs "${clone_path}/.config/zsh/zsh_exports" "${HOME}/.config/zsh/zsh_exports" \
    && ln -fs "${clone_path}/.config/zsh/zsh_git" "${HOME}/.config/zsh/zsh_git" \
    && ln -fs "${clone_path}/.config/zsh/zsh_plugins" "${HOME}/.config/zsh/zsh_plugins" \
    && ln -fs "${clone_path}/.local/bin/update-zsh-plugins" "${HOME}/.local/bin/update-zsh-plugins"

###############################################################################
# Done!
###############################################################################

cat << EOF
Everything was installed successfully!

Check out the README file on GitHub to do 1 quick thing manually:

https://github.com/jknsware/.monkeydotfiles

You can safely close this terminal.

The next time you open your terminal zsh will be ready to go!
EOF

exit 0