#!/bin/bash

set -e

function print_usage {
  echo
  echo "USAGE: monkeydotfiles [OPTIONS]"
  echo
  echo "This script will bootstrap all the user config files for:"
  echo "  - aws-auth"
  echo "  - bash_profile"
  echo "  - git"
  echo "  - liquidprompt"
  echo "  - lpass"
  echo "  - ssh"
  echo "  - sublime"
  echo "  - vscode"
  echo
  echo "Options:"
  echo
  echo -e "  --all\t\tBootstrap all the config files."
  echo -e "  --backup\tBackup all the existing config files. Good way to preserve everything while testing. Runs by default."
  echo -e "  --sublime\tOnly bootstrap Sublime Text 3 files."
  echo -e "  --vscode\tOnly bootstrap Visual Studio Code files."
  echo
}

files_list=(
  /usr/local/bin/aws-auth
  "${HOME}"/.bash_profile
  "${HOME}"/.bashrc
  "${HOME}"/.bash_aliases
  "${HOME}"/.git-autocompletion.sh
  "${HOME}"/.gitattributes
  "${HOME}"/.gitconfig
  "${HOME}"/.config/liquidprompt
  "${HOME}"/.lpass/username
  "${HOME}"/.ssh
)

function backup_files () {
  echo
  echo "INFO: Backing up files"

  # Move /backup if it still exists
  if [ -d "${HOME}"/.monkeydotfiles/backup ] ; then
    mv "${HOME}"/.monkeydotfiles/backup "${HOME}"/.monkeydotfiles/_backup
  fi

  # Create _backup folder if needed
  if [ ! -d "${HOME}"/.monkeydotfiles/_backup/ ] ; then
    mkdir -v "${HOME}"/.monkeydotfiles/_backup
  fi

  # Create a copy of original files
  for _files in "${files_list[@]}" ; do
    if [[ -e $_files ]] ; then
      cp -vR "$_files" "${HOME}"/.monkeydotfiles/_backup/
    fi
  done
}

function symlink_env () {
  echo
  echo "INFO: Symlinking environment"

  # Delete all the files
  for _files in "${files_list[@]}" ; do
    if [[ -e $_files ]] ; then
      rm -rf "$_files"
    fi
  done

  ln -fsv "${HOME}"/.monkeydotfiles/aws-auth/aws-auth /usr/local/bin/aws-auth
  ln -fsv "${HOME}"/.monkeydotfiles/bash/bash_profile "${HOME}"/.bash_profile
  ln -fsv "${HOME}"/.monkeydotfiles/git "${HOME}"/.git
  ln -fsv "${HOME}"/.monkeydotfiles/git/gitconfig "${HOME}"/.gitconfig
  ln -fsv "${HOME}"/.monkeydotfiles/liquidprompt/liquidprompt "${HOME}"/.config/liquidprompt
  ln -fsv "${HOME}"/.monkeydotfiles/lpass/username "${HOME}"/.lpass/username
  ln -fsv "${HOME}"/.monkeydotfiles/ssh "${HOME}"/.ssh
}

function symlink_sublime () {
  
  function close_sl () {
    local pid=""

    pid="$(ps -A | grep '/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text' | grep -v 'grep' | awk '{print $1}')"

    kill "$pid"
  }

  close_sl

  # Remove all the current/default installed packages or settings
  rm -rf "${HOME}"/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/*
  rm -rf "${HOME}"/Library/Application\ Support/Sublime\ Text\ 3/Packages/*

  # Symlink the Package Control file
  ln -fsv "${HOME}"/.monkeydotfiles/sublime/installedpackages/Package\ Control.sublime-package "${HOME}"/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/

  # Symlink all the settings files
  ln -fsv "${HOME}"/.monkeydotfiles/sublime/user "${HOME}"/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

  # Open Sublime and wait 30s for it to install everything
  echo "###############################################"
  echo
  echo "SUBLIME IS INSTALLING PACKAGES"
  echo "PLEASE WAIT TILL AFTER IT CLOSES TO USE SUBLIME"
  echo
  echo "###############################################"
  sublime
  sleep 30

  # Close Sublime again
  close_sl
}

function symlink_vscode () {
  
  function close_co () {
    local pid=""

    pid="$(ps -A | grep '/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron' | grep -v 'grep' | awk '{print $1}')"
    kill "$pid"
  }

  close_co

  # Remove all the current/default installed packages or settings
  # rm -rf "${HOME}"/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/*
  # rm -rf "${HOME}"/Library/Application\ Support/Sublime\ Text\ 3/Packages/*

  # Symlink the Portable Code folder
  ln -fsv "${HOME}"/.monkeydotfiles/vscode/code-portable-data /usr/local/bin/code-portable-data/

  # Open VS Code and wait 30s for it to install everything
  echo "###############################################"
  echo
  echo "VS CODE IS INSTALLING PACKAGES"
  echo "PLEASE WAIT TILL AFTER IT CLOSES TO USE VS CODE"
  echo
  echo "###############################################"
  code
  sleep 30

  # Close VS Code again
  close_co
}

function source_bash () {
  echo
  echo "INFO: Sourcing .bash_profile"
  source "${HOME}"/.bash_profile
}

function fix_ssh_perms () {
  echo
  echo "INFO: Fixing SSH file permissions"

  ssh_files=$(find -L "${HOME}"/.ssh -depth +1 \! -name "*.pub" -type f)

  for _ssh_files in "${ssh_files[@]}" ; do
    chmod 400 "${_ssh_files}"
  done
}

function install () {
  local _backup=false
  local _env=false
  local _sublime=false
  local _vscode=false

  while [[ $# -gt 0 ]]; do
    local key="$1"

    case "$key" in
      --all)
        _backup=true
        _env=true
        _vscode=true
        shift
        ;;
      --backup)
        _backup=true
        shift
        ;;
      --sublime)
        _sublime=true
        shift
        ;;
      --vscode)
        _vscode=true
        shift
        ;;
      --help)
        print_usage
        exit 1
        ;;
      *)
        echo "ERROR!"
        exit 1
        ;;
    esac
  done

  if [[ "$_backup" = true && "$_env" = true && "$_vscode" = true ]] ; then
    backup_files
    symlink_env
    symlink_vscode
    source_bash
    fix_ssh_perms

    echo
    echo "monkeydotfiles --all complete"
  elif [[ "$_backup" = true && "$_env" = false && "$_vscode" = false ]] ; then
    backup_files

    echo
    echo "monkeydotfiles --backup complete"
  elif [[ "$_vscode" = true && "$_env" = false && "$_backup" = false ]]; then
    symlink_vscode

    echo
    echo "monkeydotfiles --vscode complete"
  fi
}

install "$@"
