#!/bin/sh
#
# A git hook to make sure user.email exists before committing

EMAIL=$(git config user.email)

if [ -z "$EMAIL" ]; then
  # user.email is empty
  echo "ERROR: [pre-commit hook] Aborting commit because user.email is missing."
  echo "Configure user.email for this repository by running '$ git config user.email name@example.com'."
  echo "Make sure not to configure globally and use the correct email."
  exit 1
else
  # user.email is not empty
  exit 0
fi

# # A git hook to make sure .circleci/config.yml is formatted correctly

# # The following line is needed by the CircleCI Local Build Tool (due to Docker interactivity)
# exec < /dev/tty

# # If validation fails, tell Git to stop and provide error message. Otherwise, continue.
# if ! eMSG=$(circleci config validate -c .circleci/config.yml); then
#   echo "CircleCI Configuration Failed Validation."
#   echo "$eMSG"
#   exit 1
# fi
