#!/bin/bash

# ea - Alias for editing monkeydotfiles
alias em='sl ~/.monkeydotfiles'

# sm - Alias for sourcing monkeydotfiles
alias sm='source ~/.bash_profile'

##### ls - ls alias configured
#
# Set 'ls' to all, human readable, long format, display helpful info, and color
alias ll='ls -ahlFGL'

# Set 'python' to be Python3 on cmd line
alias python=python3

# Set 'python2' to be Python2 on cmd line
alias python2=/usr/bin/python2.7

# Set 'pip' to be pip3 on cmd line
alias pip=pip3

# Set 'pip2' to be pip2 on cmd line
alias pip2='/usr/local/bin/pip'

# Set 'gc' to be gcloud on cmd line
alias gc=gcloud

# Set 'vagrant destroy --force' on cmd ling
alias vdf='vagrant destroy --force'

# Set 'sl' to Sublime
ln -sf "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
alias sl=sublime

# Set 'fragrant' to vagrant
alias fragrant=vagrant

# Alias changing directories by specifying number of levels up
function cd_up() {
  cd $(printf "%0.s../" $(seq 1 $1 ));
}
alias 'cd..'='cd_up'

# Cht.sh
alias cheat=~/.monkeydotfiles/cheat/cht.sh

#############################
# AWS and Healthline Specific
#############################

# Bastion script
alias bastion=~/.monkeydotfiles/ssh/bastion

# List the tunnels and their PIDs
# Use `kill <pid-num>` to kill the tunnel
alias tunnels="ps aux | grep ssh | grep L | grep -v ssh-agent | grep -v grep | awk '{print \$2, \$13}' OFS='   ' "

# Create a tunnel to the target instance
# The $@ needs the port number from the bastion function
alias ss='ssh jware@localhost -p $@'

# Describe EC2 instances
alias disc-ec2="aws ec2 describe-instances | jq -r '.Reservations[].Instances[] | [.InstanceId, .NetworkInterfaces[].PrivateIpAddress, (.Tags[]|select(.Key==\"Name\")|.Value)]'"

# AWS whoami
function awswhoami () {
  echo "The command is: aws sts get-caller-identity"
  aws sts get-caller-identity
}



echo "  Bash aliases sourced."
