#!/bin/bash

function sourcebash () {
  local sourcefiles=()

  sourcefiles=(
    "${HOME}"/.monkeydotfiles/bash/bash_exports
    "${HOME}"/.monkeydotfiles/bash/bash_aliases
    "${HOME}"/.monkeydotfiles/bash/bash_docker
    "${HOME}"/.monkeydotfiles/bash/bash_git
    "${HOME}"/.monkeydotfiles/bash/bash_lpass
    )

  for file in "${sourcefiles[@]}"; do
    source "${file}"
  done
}

sourcebash

# default file permissions
umask 002

# iterm2 Shell Integration
#test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Only load Liquid Prompt in interactive shells, not from a script or from scp
if [ -f ~/liquidprompt/liquidprompt ]; then
  . ~/liquidprompt/liquidprompt
fi

echo "  Bash profile sourced."
