#!/bin/bash

# ea - Alias for editing monkeydotfiles
alias em='code ${HOME}/.monkeydotfiles'

# sm - Alias for sourcing monkeydotfiles
alias sm='source ${HOME}/.bash_profile'

##### ls - ls alias configured
#
# Set 'ls' to all, human readable, long format, display helpful info, and color
alias ll='ls -ahlFG'

# Set 'python' to be Python3 on cmd line
alias py3=python3

# Set 'python2' to be Python2 on cmd line
alias py2=/usr/bin/python2.7

# Set 'pip2' to be pip2 on cmd line
alias pip2='/usr/local/bin/pip'

# Set 'gc' to be gcloud on cmd line
alias gc=gcloud

# Set 'vagrant destroy --force' on cmd ling
alias vdf='vagrant destroy --force'

# Set 'sl' to Sublime
ln -sf "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
alias sl=sublime

# Set Visual Studio Code to 'co' 
ln -sf "/usr/local/bin/Visual Studio Code.app/Contents/Resources/app/bin/code" /usr/local/bin/code
alias co=code

# Set 'fragrant' to vagrant
alias fragrant=vagrant

# Alias changing directories by specifying number of levels up
function cd_up() {
  cd $(printf "%0.s../" $(seq 1 $1 ));
}
alias 'cd..'='cd_up'

# Cht.sh
alias cheat=${HOME}/.monkeydotfiles/cheat/cht.sh

# terragrunt functions
function tgaaa() {
  echo "Terragrunt Apply Auto-Approve"
  terragrunt apply -auto-approve
}

function tgp() {
  echo "Terragrunt Plan"
  terragrunt plan
}

function tgo() {
  echo "Terragrunt Output"
  terragrunt output
}

function tgddd() {
  echo "BURN IT ALL DOWN!!!"
  terragrunt destroy
}

#############################
# AWS and Healthline Specific
#############################

# List EC2 IPs
alias ec2-ips="aws ec2 describe-instances | jq -r '.Reservations[].Instances[] | [.InstanceId, .NetworkInterfaces[].PrivateIpAddress, (.Tags[]|select(.Key==\"Name\")|.Value)]'"

# AWS whoami
function awswhoami () {
  echo "The command is: aws sts get-caller-identity"
  aws sts get-caller-identity
}



echo "  Bash aliases sourced."
