#!/bin/bash

function sourcebash () {
  local sourcefiles=()

  sourcefiles=(
    ~/.monkeydotfiles/bash/bash_exports
    ~/.monkeydotfiles/bash/bash_aliases
    ~/.monkeydotfiles/bash/bash_docker
    ~/.monkeydotfiles/bash/bash_git
    ~/.monkeydotfiles/bash/bash_lpass
    )

  for file in "${sourcefiles[@]}"; do
    source "${file}"
  done

  echo "INFO: Files sourced."
}

sourcebash

# default file permissions
umask 002

# iterm2 Shell Integration
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Only load Liquid Prompt in interactive shells, not from a script or from scp
[[ $- = *i* ]] && source ~/git/home/liquidprompt/liquidprompt
