#!/bin/bash

# Alias all the "aws-auth" scripts with "lpass"
# https://github.com/jknsware/lastpass-with-aws

alias aws-auth-security='eval "$(lpass show aws-auth-security --field Param1; lpass show aws-auth-security --field Param2)"'
alias aws-auth-shared_services='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-shared_services-arn --username)"'
alias aws-auth-sandbox='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-sandbox-arn --username)"'  
alias aws-auth-buddy-qa='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-buddy-qa-arn --username)"'
alias aws-auth-buddy-dev='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-buddy-dev-arn --username)"'
alias aws-auth-buddy-preprod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-buddy-preprod-arn --username)"'
alias aws-auth-buddy-prod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-buddy-prod-arn --username)"'
alias aws-auth-fe-prototype='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-fe-prototype-arn --username)"'
alias aws-auth-act-prod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-act-prod-arn --username)"'
alias aws-auth-act-dev='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-act-dev-arn --username)"'
alias aws-auth-act-staging='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-act-staging-arn --username)"'
alias aws-auth-fe-staging='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-fe-staging-arn --username)"'
alias aws-auth-fe-preprod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-fe-preprod-arn --username)"'
alias aws-auth-fe-prod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-fe-prod-arn --username)"'
alias aws-auth-data='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-data-arn --username)"'
alias aws-auth-backend='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-backend-arn --username)"'
alias aws-auth-gr8-staging='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-gr8-staging-arn --username)"'
alias aws-auth-gr8-preprod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-gr8-preprod-arn --username)"'
alias aws-auth-gr8-prod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-gr8-prod-arn --username)"'
alias aws-auth-post-prod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-post-prod-arn --username)"'
alias aws-auth-post-staging='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-post-staging-arn --username)"'
alias aws-auth-mnto-staging='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-mnto-staging-arn --username)"'
alias aws-auth-mnto-prod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-mnto-prod-arn --username)"'
alias aws-auth-mnt-prod='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-mnt-prod-arn --username)"'
alias aws-auth-mnt-staging='eval "$(lpass show aws-auth-security --field Param1; lpass show hl-mnt-staging-arn --username)"'

echo "  Bash lpass sourced."
