#!/bin/bash

##### ea - alias for editing aliases
#
# When setting up a new aliases file, or having creating a new file.. About every time after editing an aliases file, I source it.
# This alias makes editing alias a bit easier and they are useful right away. Note if the source failed, it will not 
# echo "aliases sourced". Sub in gedit for your favorite editor, or alter for ksh, sh, etc.
alias ea='sl -w ~/.monkeydotfiles/bash/bash_aliases; source ~/.bash_aliases && source $HOME/.bash_aliases && echo "aliases sourced --ok."'

##### ls - ls alias configured
#
# Set 'ls' to all, human readable, long format, display helpful info, and color
alias ll='ls -ahlFG'

# Set 'python' to be Python3 on cmd line
alias python=python3

# Set 'python2' to be Python2 on cmd line
alias python2=/usr/bin/python2.7

# Set 'pip' to be pip3 on cmd line
alias pip=pip3

# Set 'pip2' to be pip2 on cmd line
alias pip2='/usr/local/bin/pip'

# Set 'gc' to be gcloud on cmd line
alias gc=gcloud

# Set 'vagrant destroy --force' on cmd ling
alias vdf='vagrant destroy --force'

# Set 'sl' to Sublime
# Symlink created with "ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime"
alias sl=sublime

# Set 'fragrant' to vagrant
alias fragrant=vagrant

# Alias changing directories by specifying number of levels up
function cd_up() {
  cd $(printf "%0.s../" $(seq 1 $1 ));
}
alias 'cd..'='cd_up'

# Cht.sh
alias cheat=/usr/local/bin/cht.sh
