#!/bin/bash

#####################
# History Control
#####################

export HISTSIZE=20000
export HISTFILESIZE=$HISTSIZE
export HISTTIMEFORMAT="[%F %T] "
# Ignore duplicates written in sequence
export HISTCONTROL=ignoredups
export HISTIGNORE="&:l:ls:lt:la:lsa:ll:exit:history"

# history_sync: After every command, append latest commands to hist file, then clear shell history, and re-read all from file
# https://github.com/RichVel/nicer-bash-prompt/blob/master/nicer-bash-prompt
# https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows
history_sync() { 
  history -a; history -c; history -r; 
}

# Force history commit after every command:
PROMPT_COMMAND="$history_sync"

# Append to the history file, don't overwrite it
shopt -s histappend

#################
# Completions
#################

# AWS Command Completion
# complete -C '/usr/local/bin/aws_completer' aws
if [ -f /usr/local/bin/aws_completer ] ; then
  complete -C /usr/local/bin/aws_completer aws
fi

# Source gcloud
if [ -f /usr/local/bin/google-cloud-sdk/path.bash.inc ] ; then
  source "/usr/local/bin/google-cloud-sdk/path.bash.inc"
fi

# Source gcloud completion
if [ -f /usr/local/bin/google-cloud-sdk/completion.bash.inc ] ; then
  source "/usr/local/bin/google-cloud-sdk/completion.bash.inc"
fi

# kubectl completion
# https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-mac/
source <(kubectl completion bash)

# Brew bash completion
if [[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] ; then
  . /opt/homebrew/etc/profile.d/bash_completion.sh
fi

# Source git completion
# Source - https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
if [ -f ${HOME}/.monkeydotfiles/git/git-completion.sh ] ; then
  source "${HOME}/.monkeydotfiles/git/git-completion.sh"
fi

# Source cheat completion
if [ -f ${HOME}/.monkeydotfile/cheat/cheat-completion.sh ] ; then
  source "${HOME}/.monkeydotfiles/cheat/cheat-completion.sh"
fi

# explain.sh begins
# https://www.tecmint.com/explain-shell-commands-in-the-linux-shell/
explain () {
  if [ "$#" -eq 0 ]; then
    while read  -p "Command: " cmd; do
      curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols) --data-urlencode "q=$cmd"
    done
    echo "Bye!"
  elif [ "$#" -eq 1 ]; then
    curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols) --data-urlencode "q=$1"
  else
  echo "Usage"
  echo "explain                  interactive mode."
  echo "explain 'cmd -o | ...'   one quoted command to explain it."
  fi
}

GPG_TTY=$(tty)
export GPG_TTY

#############
# Pathing
#############

# Brew curl
# For compilers to find curl you may need to set
# export PATH="/usr/local/opt/curl/bin:$PATH"

export LDFLAGS="-L/usr/local/opt/curl/lib"
export CPPFLAGS="-I/usr/local/opt/curl/include"

# Visual Studio Code
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"

# Python
# Python is controlled with pyenv. Use it.

# Pyenv PATH export
# Remember to `pyenv global 3.9.12 2.7.18` or whatever versions I have installed
export PATH="$(pyenv root)/shims:$PATH"

###################
# Misc Exports
###################

# Brew export
eval "$(/opt/homebrew/bin/brew shellenv)"

# Enable Buildkit
export DOCKER_BUILDKIT=1

# NPM Token
export NPM_TOKEN=

# Terragrunt cache location
export TERRAGRUNT_DOWNLOAD=${HOME}/.terragrunt/cache

# Terraform plugin location
export TF_PLUGIN_CACHE_DIR=${HOME}/.terraform.d/plugin-cache

# Terragrunt Local
# Use local IAM role instead of Atlantis
export TERRAGRUNT_LOCAL=true

# CirleCI Token
# export CIRCLECI_TOKEN=

# PagerDuty Token
# export PAGERDUTY_TOKEN=

# New Relic
# export NEW_RELIC_ACCOUNT_ID=
# export NEW_RELIC_API_KEY=
# export NEW_RELIC_ADMIN_API_KEY=
# export NEW_RELIC_REGION=us

echo "  Bash exports sourced."
