#!/bin/bash

#################
# Git Aliases
#################

# Also check ~/.monkeydotfiles/git/gitconfig for strict git aliases

# Git - Tag help
function gittag()
{
  echo "  To add tags:"
  echo "  git tag -a v0.1.18 -m \"Adds this functionality\""
  echo "  git push origin --tags"
  echo "   "
  echo "  To delete tags:"
  echo "  git tag -d tag-name"
  echo "  git push origin :refs/tags/tag-name"
}

# Alias changing to main git repos
alias cdm="cd ~/git/hl/infrastructure-modules"
alias cdl="cd ~/git/hl/infrastructure-live"
alias cdhl="cd ~/git/hl"
alias cdho="cd ~/git/home"

#################
# Git Exports
#################

# Export GITHUB_OATH_TOKEN
export GITHUB_OAUTH_TOKEN=812a5049da0a91a8501375acf6893ed836182c83

echo "  Bash git sourced."
